//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoromotoAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDCoromotoEntities : DbContext
    {
        public BDCoromotoEntities()
            : base("name=BDCoromotoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tActivos> tActivos { get; set; }
        public virtual DbSet<tCategorias> tCategorias { get; set; }
        public virtual DbSet<tContactenos> tContactenos { get; set; }
        public virtual DbSet<tEmpleados> tEmpleados { get; set; }
        public virtual DbSet<tEvaluaciones> tEvaluaciones { get; set; }
        public virtual DbSet<tFacturas> tFacturas { get; set; }
        public virtual DbSet<tHabitaciones> tHabitaciones { get; set; }
        public virtual DbSet<tLimpiezas> tLimpiezas { get; set; }
        public virtual DbSet<tMetodoPago> tMetodoPago { get; set; }
        public virtual DbSet<tMonedas> tMonedas { get; set; }
        public virtual DbSet<tNominas> tNominas { get; set; }
        public virtual DbSet<tPermisos> tPermisos { get; set; }
        public virtual DbSet<tReservas> tReservas { get; set; }
        public virtual DbSet<tRoles> tRoles { get; set; }
        public virtual DbSet<tTiposHabitaciones> tTiposHabitaciones { get; set; }
        public virtual DbSet<tTurnos> tTurnos { get; set; }
        public virtual DbSet<tUsuario> tUsuario { get; set; }
        public virtual DbSet<tVacaciones> tVacaciones { get; set; }
        public virtual DbSet<tVillas> tVillas { get; set; }
    }
}
