//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoromotoAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tActivos
    {
        public int IdActivo { get; set; }
        public int IdHabitacion { get; set; }
        public string Nombre { get; set; }
        public string Modelo { get; set; }
        public string NumeroSerie { get; set; }
        public string Descripcion { get; set; }
        public int IdCategoria { get; set; }
    
        public virtual tCategorias tCategorias { get; set; }
        public virtual tHabitaciones tHabitaciones { get; set; }
    }
}
