//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoromotoAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEmpleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tEmpleados()
        {
            this.tEvaluaciones = new HashSet<tEvaluaciones>();
            this.tLimpiezas = new HashSet<tLimpiezas>();
            this.tNominas = new HashSet<tNominas>();
            this.tTareas = new HashSet<tTareas>();
            this.tVacaciones = new HashSet<tVacaciones>();
        }
    
        public int ConsecutivoEmp { get; set; }
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string CorreoElectronico { get; set; }
        public string Telefono { get; set; }
        public string FotoPerfil { get; set; }
        public string Contrasenna { get; set; }
        public int ConsecutivoRol { get; set; }
        public bool Activo { get; set; }
        public bool TieneContrasennaTemp { get; set; }
        public System.DateTime FechaVencimientoTemp { get; set; }
        public int IdVilla { get; set; }
        public int IdTurno { get; set; }
        public int Vacaciones { get; set; }
        public int HorasTrabajadas { get; set; }
        public Nullable<bool> SesionActiva { get; set; }
        public Nullable<System.DateTime> UltimaSesion { get; set; }
    
        public virtual tRoles tRoles { get; set; }
        public virtual tTurnos tTurnos { get; set; }
        public virtual tVillas tVillas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEvaluaciones> tEvaluaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tLimpiezas> tLimpiezas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNominas> tNominas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTareas> tTareas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVacaciones> tVacaciones { get; set; }
    }
}
