//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoromotoAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNominas
    {
        public int IdNomina { get; set; }
        public int IdEmpleado { get; set; }
        public decimal Salario { get; set; }
        public decimal Bono { get; set; }
        public decimal Multa { get; set; }
        public decimal Total { get; set; }
    
        public virtual tEmpleados tEmpleados { get; set; }
    }
}
